# Import Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Load 
df = pd.read_csv('../data/train.csv')
df.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,price
0,1,102.7,178.4,68.0,54.8,2910,140,3.78,3.12,8.0,...,0,0,0,0,0,0,1,0,0,16503.0
1,1,93.7,157.3,63.8,50.8,2128,98,3.03,3.39,7.6,...,0,0,0,0,0,0,0,1,0,7957.0
2,3,94.5,159.3,64.2,55.6,2254,109,3.19,3.40,8.5,...,0,0,0,0,0,0,1,0,0,11595.0
3,3,95.9,173.2,66.3,50.2,2833,156,3.58,3.86,7.0,...,0,0,0,0,0,0,0,1,0,12629.0
4,0,96.1,181.5,66.5,55.2,2579,132,3.46,3.90,8.7,...,0,0,0,0,0,0,1,0,0,9295.0

# Feature Engineering

In [3]:
df['car_width_length'] = np.sqrt((df.carwidth + df.carlength))
df.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,price,car_width_length
0,1,102.7,178.4,68.0,54.8,2910,140,3.78,3.12,8.0,...,0,0,0,0,0,1,0,0,16503.0,15.697133
1,1,93.7,157.3,63.8,50.8,2128,98,3.03,3.39,7.6,...,0,0,0,0,0,0,1,0,7957.0,14.869432
2,3,94.5,159.3,64.2,55.6,2254,109,3.19,3.40,8.5,...,0,0,0,0,0,1,0,0,11595.0,14.949916
3,3,95.9,173.2,66.3,50.2,2833,156,3.58,3.86,7.0,...,0,0,0,0,0,0,1,0,12629.0,15.475788
4,0,96.1,181.5,66.5,55.2,2579,132,3.46,3.90,8.7,...,0,0,0,0,0,1,0,0,9295.0,15.748016

# Select Features

In [4]:
features = df.drop(columns='price')
target = df.price

In [5]:
from sklearn.feature_selection import mutual_info_regression, SelectKBest

In [7]:
scores = mutual_info_regression(
    features,
    target,
    discrete_features='auto',
    n_neighbors=3,
    copy=True,
    random_state=33,
)
scores.shape

(49,)